---
title: "final project"
author: "Yuchen Zhang"
date: "2022-12-12"
output: github_document
---
```{r, include=FALSE}
library(tidyverse)
library(dplyr)
library(ggplot2)
```

### Distribution of Data

```{r}
Body_df = readxl::read_excel("data/body_density_data.xlsx")
summary(Body_df)
```


```{r}
ggplot(Body_df, aes(x=bodyfat_brozek)) + 
 geom_histogram(aes(y=..density..), color="white", fill="blue",binwidth = 1)+
 geom_density(alpha=.2)+
 labs(title="Distributions of body fat measured in Brozek method")

```

```{r}
colnames = colnames(Body_df)

for (i in 5:17){
  plot = 
ggplot(Body_df, aes_string(x=colnames[i])) + 
 geom_histogram(aes(y=..density..), color="white", fill="blue",binwidth = 1)+
 geom_density(alpha=.2)+
 labs(title=sprintf("Distributions of %s", colnames[i]) )
  
  print(plot)
}
```

```{r,message = FALSE, warning = FALSE}
for (i in 5:17){
  plot = 
  Body_df %>% 
    ggplot(aes_string(x = colnames[i], y = "bodyfat_brozek"))+geom_point()+geom_smooth(method = 'lm', se = TRUE, color = 'red')+
    labs(title = sprintf("Scatter plot for body fat against %s", colnames[i]) )+
    ylab("Body Fat (Brozek)")
  
  print(plot)
}
```

```{r}
bodyfat_selected = 
  Body_df %>% 
  dplyr::select(-id,-bodyfat_siri,-body_density)
```

